import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";
import LayoutWrapper from "@/components/LayoutWrapper";
import Footer from "@/components/footer";
const roboto = Roboto({
  subsets: ['latin']
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
<<<<<<< HEAD
      <html lang="en">
=======
    <html  >
>>>>>>> 0f315f58f4c4ec01675f158324af97213caa76fa
      <body
          className={`${geistSans.variable} ${geistMono.variable} ${roboto.className} antialiased`}
      >
      {/* <LayoutWrapper>{children}</LayoutWrapper> */}
      <div>{children}</div>
      </body>
      </html>
  );
}





















