import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";
import LayoutWrapper from "@/components/LayoutWrapper";
import Footer from "@/components/footer";
import {Montserrat} from "next/font/google";
import { SessionProvider } from "next-auth/react";

const roboto = Roboto({
    subsets: ['latin']
});
const montserrat = Montserrat({
    subsets: ['latin']
});
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "TaskLinker",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${montserrat.className} antialiased`}
        >
            
        <LayoutWrapper>{children}</LayoutWrapper>
        </body>
        </html>
    );
}
