import type { Metadata } from "next";
import "./globals.css";
<<<<<<< HEAD
import { Geist, Geist_Mono, Roboto } from "next/font/google";

=======
import { Roboto } from "next/font/google";
import LayoutWrapper from "@/components/LayoutWrapper";
const roboto = Roboto({
  subsets: ['latin']
})
>>>>>>> 6b36369 (reslove problem of Register)
const geistSans = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
    subsets: ["latin"],
    variable: "--font-geist-mono",
});

const roboto = Roboto({
    subsets: ["latin"],
    variable: "--font-roboto",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
<<<<<<< HEAD
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
=======
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.className} antialiased`}
      >
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );

>>>>>>> 6b36369 (reslove problem of Register)
}




















